import { Ticket } from "./domain";

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

export const mockTickets: Ticket[] = [
  {
    id: "ticket-1",
    externalId: "EXT-4321",
    linkExterno: "https://example.com/tickets/EXT-4321",
    empresa: "VE Fortaleza",
    chassiOuMaquina: "310L-ABC123",
    tipoLeadOrigem: "WhatsApp",
    criadoEm: daysAgo(1),
    status: "em_andamento",
    virouOS: false,
    leadId: "lead-1",
  },
  {
    id: "ticket-2",
    externalId: "EXT-2310",
    linkExterno: "https://example.com/tickets/EXT-2310",
    empresa: "VE Mossoro",
    chassiOuMaquina: "850J-FOO777",
    tipoLeadOrigem: "Telefone",
    criadoEm: daysAgo(4),
    status: "aberto",
    virouOS: false,
    leadId: "lead-2",
  },
  {
    id: "ticket-3",
    externalId: "EXT-9988",
    linkExterno: "https://example.com/tickets/EXT-9988",
    empresa: "VE Fortaleza",
    chassiOuMaquina: "210K-BAR456",
    tipoLeadOrigem: "Landing Page",
    criadoEm: daysAgo(9),
    status: "fechado",
    virouOS: true,
    leadId: "lead-4",
  },
  {
    id: "ticket-4",
    externalId: "EXT-5511",
    linkExterno: "https://example.com/tickets/EXT-5511",
    empresa: "VE Cariri",
    chassiOuMaquina: "730P-GHI555",
    tipoLeadOrigem: "Feira",
    criadoEm: daysAgo(2),
    status: "em_andamento",
    virouOS: true,
    leadId: "lead-7",
  },
  {
    id: "ticket-5",
    externalId: "EXT-7766",
    linkExterno: "https://example.com/tickets/EXT-7766",
    empresa: "VE Recife",
    chassiOuMaquina: "520M-NEW999",
    tipoLeadOrigem: "WhatsApp",
    criadoEm: daysAgo(16),
    status: "fechado",
    virouOS: false,
  },
];
